exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: f6188ce6dcde3fcad381c52ecc74374e7d0579c9
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 32119baf69e913a72f2e1b1fbe0d56921b670ebb
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        files: src/
  - repo: https://github.com/PyCQA/flake8
    rev: 3ce76158a0e18605e9701bd3a2a25716fea411de
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 071c722d2b36924e30c998a415609176e247fce5
    hooks:
      - id: pdb-vars
  - repo: https://github.com/hadialqattan/pycln
    rev: 570395824fcca251f7083e2d71fb52ac0dd7d5aa
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
