exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: b0eed7c6bd5f04f0ea6b6592d8a3ab63d8a01252
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 18c2496e4ca0da8d25f0561bd51c29befea02b28
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 32119baf69e913a72f2e1b1fbe0d56921b670ebb
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        files: asserto/
  - repo: https://github.com/PyCQA/flake8
    rev: e8f9eb369a7b300a0517e2f783396f8bec19643a
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 071c722d2b36924e30c998a415609176e247fce5
    hooks:
      - id: pdb-vars
  - repo: https://github.com/hadialqattan/pycln
    rev: 70874fe5d5d1e32b928e515347126059e6c8544d
    hooks:
      - id: pycln
        args: [--config=pyproject.toml, --all]
