site_name: Asserto documentation
site_url: https://www.google.com
nav:
    - Overview: index.md
    - String Assertions: strings.md
    - Generic Assertions: generic.md
theme:
  name: material
  features:
    - content.code.annotate
plugins:
    - search
    - mkdocstrings
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
