site_name: Asserto documentation
site_url: https://www.google.com
nav:
    - Overview: index.md
    - Assertions: assertions.md
theme:
  name: material
  features:
    - content.code.annotate
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            rendering:
              show_source: false
        watch:
          - asserto/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
