name: asserto testing
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py38",
          "ubuntu-py39",
          "ubuntu-py310",
          "win-py38",
          "win-py39",
          "win-py310",
        ]
        include:
          - name: "ubuntu-py38"
            python: "3.8"
            operating_system: "ubuntu-20.04"
            tox_env: "py38"
            do_cov: false
          - name: "ubuntu-py39"
            python: "3.9"
            operating_system: "ubuntu-20.04"
            tox_env: "py39"
            do_cov: false
          - name: "ubuntu-py310"
            python: "3.10"
            operating_system: "ubuntu-20.04"
            tox_env: "py310"
            do_cov: true
          - name: "windows-py38"
            python: "3.8"
            operating_system: "windows-latest"
            tox_env: "py38"
            do_cov: false
          - name: "windows-py39"
            python: "3.9"
            operating_system: "windows-latest"
            tox_env: "py39"
            do_cov: false
          - name: "windows-py310"
            python: "3.10"
            operating_system: "windows-latest"
            tox_env: "py310"
            do_cov: false
    runs-on: ${{ matrix.operating_system }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip install poetry
          pip --version
          tox --version
          poetry --version

      - name: Test without coverage
        if: "! matrix.do_cov"
        run: |
          tox -e ${{ matrix.tox_env }}

      - name: Test with coverage
        if: "matrix.do_cov"
        run: |
          tox -e ${{ matrix.tox_env }}

      - name: Generate cov report
        if: "matrix.do_cov"
        run: |
          tox -e report_cov

      - name: Upload to CodeCov
        if: "matrix.do_cov"
        uses: codecov/codecov-action@v2
        with:
          flags: asserto unit tests
          fail_ci_if_error: true
          verbose: true
